[database]
conn_string = postgres://{{ env "LIVDOT_DATABASE_USER" }}:{{ env "LIVDOT_DATABASE_PASSWORD" }}@{{ env "LIVDOT_DATABASE_HOST" }}:{{ env "LIVDOT_DATABASE_PORT" }}/{{ env "LIVDOT_DATABASE_NAME" }}?sslmode=disable
version_table = public.schema_version

